###
POST http://localhost:9000/api/director HTTP/1.1
Content-Type: application/json

{
    "dir_id": 6,
    "dir_fname": "James",
    "dir_lname": "Gun"
}

###
GET http://localhost:9000/api/director HTTP/1.1

###
GET http://localhost:9000/api/director/5 HTTP/1.1

###
PUT http://localhost:9000/api/director/6 HTTP/1.1
Content-Type: application/json

{
    "dir_id": 6,
    "dir_fname": "James",
    "dir_lname": "Gun Gun"
}

###
DELETE http://localhost:9000/api/director/6 HTTP/1.1