###
POST http://localhost:9000/api/ratings HTTP/1.1
Content-Type: application/json

{
    "rev_id": 3,
    "mov_id": 3,
    "rev_stars": 180,
    "num_o_ratings": 135
}

###
GET http://localhost:9000/api/ratings HTTP/1.1

###
GET http://localhost:9000/api/ratings/1 HTTP/1.1

###
DELETE http://localhost:9000/api/ratings/3 HTTP/1.1

###
PUT http://localhost:9000/api/ratings/2 HTTP/1.1
Content-Type: application/json

{
    "rev_id": 2,
    "mov_id": 2,
    "rev_stars": 130,
    "num_o_ratings": 40
}
