###
POST http://localhost:9000/api/movies HTTP/1.1
Content-Type: application/json

{
    "mov_id": 3,
    "mov_title": "Batman",
    "mov_year": 2008,
    "mov_time": 180,
    "mov_lang": "ENG",
    "mov_dt_rel": "09-12-2008",
    "mov_rel_country": "UK"
}

###
GET http://localhost:9000/api/movies HTTP/1.1

###
GET http://localhost:9000/api/movies/2 HTTP/1.1

###
GET http://localhost:9000/api/movies/title/Ant%20Man HTTP/1.1

###
DELETE http://localhost:9000/api/movies/5 HTTP/1.1

###
PUT http://localhost:9000/api/movies/2 HTTP/1.1
Content-Type: application/json

{
    "mov_id": 2,
    "mov_title": "Ant Man",
    "mov_year": 2023,
    "mov_time": 130,
    "mov_lang": "ENG",
    "mov_dt_rel": "16-02-2023",
    "mov_rel_country": "USA"
}